services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Rafli123+
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: rafli
      MYSQL_PASSWORD: Rafli123+
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

volumes:
  db_data: 